apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tesla-telemetry.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tesla-telemetry.labels" . | nindent 4 }}
data:
  KAFKA_TOPIC: {{ .Values.config.kafka.topic | quote }}
  KAFKA_CONSUMER_GROUP: {{ .Values.config.kafka.consumerGroup | quote }}
  PORT: {{ .Values.config.port | quote }}
  ENABLE_SUPABASE: {{ .Values.config.enableSupabase | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tesla-telemetry.fullname" . }}-vehicle-vins
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tesla-telemetry.labels" . | nindent 4 }}
data:
{{- range $index, $vehicle := .Values.logger.vehicles }}
  vin-{{ $index }}: {{ $vehicle.vin | quote }}
{{- end }}

